// Regenerates stages.js deterministically:  node sudoku/gen-stages.mjs
// Every puzzle has a unique solution and is solvable by the human-style grader in logic.js.
import { writeFileSync } from 'node:fs';
import { rng, randomSolution, dig, grade, countSolutions, gridString } from './logic.js';

const r = rng(20261008);
const POOL = 24000;
const pool = { 1: [], 2: [], 3: [], 4: [], 5: [] };
const t0 = Date.now();
for (let k = 0; k < POOL; k++) {
  const sol = randomSolution(r), p = dig(sol, r), g = grade(p);
  if (g.level <= 5) pool[g.level].push({ p, sol, g });
}
console.log('pool', Object.fromEntries(Object.entries(pool).map(([k, v]) => [k, v.length])), Date.now() - t0, 'ms');

const givensOf = p => p.filter(v => v).length;
// Put solution digits back (symmetric pairs) while the grade level stays the same.
function addBack(item, target) {
  const p = item.p.slice();
  const empty = []; for (let i = 0; i <= 40; i++) if (!p[i]) empty.push(i);
  for (let i = empty.length - 1; i > 0; i--) { const j = (r() * (i + 1)) | 0; [empty[i], empty[j]] = [empty[j], empty[i]]; }
  for (const i of empty) {
    if (givensOf(p) >= target) break;
    const j = 80 - i, a = p[i], b = p[j];
    p[i] = item.sol[i]; p[j] = item.sol[j];
    if (givensOf(p) > target || grade(p).level !== item.g.level) { p[i] = a; p[j] = b; }
  }
  return { p, sol: item.sol, g: grade(p) };
}
const take = (lvl, n, pick = 'low') => {
  const arr = pool[lvl].sort((a, b) => a.g.score - b.g.score);
  const out = pick === 'low' ? arr.splice(0, n) : arr.splice(arr.length - n, n);
  if (out.length < n) throw new Error(`not enough level ${lvl} puzzles`);
  return out;
};
// n items spread evenly over the pool entries whose score lies in [lo, hi]
const spread = (lvl, n, lo, hi, maxGivens = 81) => {
  const arr = pool[lvl].filter(it => it.g.score >= lo && it.g.score <= hi && givensOf(it.p) <= maxGivens).sort((a, b) => a.g.score - b.g.score);
  if (arr.length < n) throw new Error(`not enough level ${lvl} puzzles in ${lo}-${hi}: ${arr.length}`);
  const out = Array.from({ length: n }, (_, k) => arr[Math.round(k * (arr.length - 1) / Math.max(1, n - 1))]);
  pool[lvl] = pool[lvl].filter(it => !out.includes(it));
  return out;
};
const lerp = (a, b, k, n) => Math.round(a + (b - a) * (n === 1 ? 0 : k / (n - 1)));

const tiers = [];
// 1-20 very easy: singles only, 45 -> 38 givens
tiers.push(take(1, 20).map((it, k) => addBack(it, lerp(45, 38, k, 20))));
// 21-45 easy: singles with fewer givens (36 -> 31), then the first locked candidates (32 -> 30)
tiers.push([...take(1, 12, 'high').map((it, k) => addBack(it, lerp(36, 31, k, 12))),
  ...take(2, 13).map((it, k) => addBack(it, lerp(32, 30, k, 13)))]);
// 46-70 medium: harder locked candidates, then naked/hidden pairs (30 -> 26 givens)
tiers.push([...spread(2, 6, 95, 115).map(it => addBack(it, 29)),
  ...take(3, 19).map((it, k) => addBack(it, lerp(30, 27, k, 19)))]);
// 71-90 hard: many pairs and every triple/quad puzzle found, near-minimal givens
const quads = pool[4].sort((a, b) => givensOf(a.p) - givensOf(b.p)).slice(0, 10);
tiers.push([...spread(3, 20 - quads.length, 125, 210, 27).map(it => addBack(it, 26)), ...quads.map(it => addBack(it, 26))]);
// 91-100 expert: X-wing / XY-wing / swordfish, minimal givens; mix techniques
const ex = pool[5].sort((a, b) => a.g.score - b.g.score);
const want = ['swordfish', 'xyWing', 'xWing'];
const expert = [];
for (const t of want) for (const it of ex.filter(e => e.g.counts[t] && givensOf(e.p) <= 26).slice(-3)) if (!expert.includes(it) && expert.length < 10) expert.push(it);
for (const it of ex.slice().reverse()) if (givensOf(it.p) <= 26) if (expert.length < 10 && !expert.includes(it)) expert.push(it);
tiers.push(expert);

const NAMES = ['입문', '초급', '중급', '고급', '전문가'];
const stages = [];
tiers.forEach((list, ti) => {
  list.sort((a, b) => a.g.level - b.g.level || a.g.score - b.g.score);
  for (const it of list) {
    if (countSolutions(it.p, 2) !== 1) throw new Error('not unique');
    stages.push({ p: gridString(it.p), s: it.sol.join(''), tier: ti, level: it.g.level, score: it.g.score, givens: givensOf(it.p),
      techs: Object.keys(it.g.counts) });
  }
});
if (stages.length !== 100) throw new Error('need 100 stages, got ' + stages.length);
for (let i = 1; i < 100; i++) if (stages[i].level < stages[i - 1].level) throw new Error('level order at ' + i);

const lines = stages.map(s => `  { p: '${s.p}', s: '${s.s}', tier: ${s.tier}, level: ${s.level}, score: ${s.score}, givens: ${s.givens} },`);
writeFileSync(new URL('./stages.js', import.meta.url), `// Generated by gen-stages.mjs (seeded, deterministic). p = puzzle (0 = empty), s = solution.
// level = hardest technique needed (1 singles, 2 pointing/claiming, 3 pairs, 4 triples/quads, 5 X-wing/XY-wing/swordfish).
export const TIERS = [
  { name: '${NAMES[0]}', from: 1, to: 20 },
  { name: '${NAMES[1]}', from: 21, to: 45 },
  { name: '${NAMES[2]}', from: 46, to: 70 },
  { name: '${NAMES[3]}', from: 71, to: 90 },
  { name: '${NAMES[4]}', from: 91, to: 100 },
];
export const STAGES = [
${lines.join('\n')}
];
`);
tiers.forEach((l, ti) => {
  const ss = stages.filter(s => s.tier === ti);
  const tech = new Set(ss.flatMap(s => s.techs));
  console.log(NAMES[ti], 'levels', [...new Set(ss.map(s => s.level))].join(','), 'givens', Math.min(...ss.map(s => s.givens)), '-', Math.max(...ss.map(s => s.givens)),
    'score', ss[0].score, '-', ss[ss.length - 1].score, [...tech].join(' '));
});
console.log('done', Date.now() - t0, 'ms');
